# -*- coding: utf-8 -*-
"""ViT_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iGE4Nhb5zuEc6RpfrVswdy1kPf4vfzg
"""

import torch
from PIL import Image
from transformers import ViTForImageClassification, ViTImageProcessor

MODEL_PATH = "./"  # 모델이 저장된 폴더 경로

try:
    processor = ViTImageProcessor.from_pretrained(MODEL_PATH)
    model = ViTForImageClassification.from_pretrained(MODEL_PATH)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval() # 추론 모드로 설정
    print(f"✅ 모델 로드 완료. 현재 Device: {device}")
except Exception as e:
    print(f"❌ 모델 로드 중 오류 발생: {e}")
    print("폴더 경로와 파일 존재 여부를 확인해주세요.")
    exit()

IMAGE_FILE_PATH = "plane4.png"

try:
    image = Image.open(IMAGE_FILE_PATH).convert("RGB")
except FileNotFoundError:
    print(f"❌ 오류: 이미지 파일 '{IMAGE_FILE_PATH}'을(를) 찾을 수 없습니다.")
    exit()

# 4. 이미지 전처리 및 텐서 생성
# processor를 사용하여 모델 입력에 맞게 이미지 크기 조정 및 정규화 수행
inputs = processor(images=image, return_tensors="pt").to(device)

with torch.no_grad():
    outputs = model(**inputs)

# 6. 결과 해석
# 로짓(logits)에서 가장 높은 확률의 클래스 인덱스를 찾습니다.
logits = outputs.logits
predicted_class_idx = logits.argmax(-1).item()

# 7. 클래스 이름으로 변환
# config.json에 저장된 id2label 정보를 사용하여 인덱스를 이름으로 변환합니다.
predicted_label = model.config.id2label[predicted_class_idx]

print("\n--- 추론 결과 ---")
print(f"예측된 클래스 인덱스: {predicted_class_idx}")
print(f"예측된 클래스 이름: **{predicted_label}**")