# -*- coding: utf-8 -*-
"""cifar10_tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6UN2YGLAvuwEWiIZcZ76cpxhSiysvDb

필요힌 파이썬 라이브러리를 임포트 한다.
"""

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from sklearn.preprocessing import LabelBinarizer
import cv2
from sklearn.metrics import classification_report

"""CIFAR10 데이터 셋을 다운로딩 한다."""

((trainX, trainY), (testX, testY)) = cifar10.load_data()

"""다운로딩 데이터 이미지를 확인한다,"""

img = cv2.resize(trainX[200], (300, 300))
cv2.imshow('win', img)
cv2.waitKey(1)
cv2.destroyAllWindows()
print(trainY[200])
img = cv2.resize(trainX[201], (300, 300))
cv2.imshow('win', img)
cv2.waitKey(1)
cv2.destroyAllWindows()
print(trainY[201])

"""입력 데이터 이미지의 노말라이징을 실행한다."""

trainX = trainX.astype("float") / 255.0
testX = testX.astype("float") / 255.0

"""입력 이미지 데이터를 flattening 한다."""

# Flattening: per a image 32*32*3 -> 1 * 3072
trainX = trainX.reshape((trainX.shape[0], 3072))
testX = testX.reshape((testX.shape[0], 3072))

"""결과 데이터값을 바니아리징을 한다."""

lb = LabelBinarizer()
trainY = lb.fit_transform(trainY)
testY = lb.transform(testY)

"""다층퍼셉트론인 신경망 모델을 만든다."""

model = Sequential()
model.add(Dense(1024, input_shape=(3072,), activation="relu"))
model.add(Dense(512, activation="relu"))
model.add(Dense(10, activation="softmax"))

"""신경망을 구성하고 트레이닝한다."""

sgd = SGD(0.01)
model.compile(loss="categorical_crossentropy", optimizer=sgd,
	metrics=["accuracy"])

H = model.fit(trainX, trainY, validation_data=(testX, testY),
	epochs=100, batch_size=32)

"""신경망 트레이닝 결과를 확인한다."""

labelNames = ["airplane", "automobile", "bird", "cat", "deer",
	"dog", "frog", "horse", "ship", "truck"]
print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1),
	predictions.argmax(axis=1), target_names=labelNames))

"""신경망 트레이닝 결과를 그래프로 확인한다."""

import matplotlib.pyplot as plt
import numpy as np
# plot the training loss and accuracy
plt.style.use("ggplot")
plt.figure()
plt.plot(np.arange(0, 100), H.history["loss"], label="train_loss")
plt.plot(np.arange(0, 100), H.history["val_loss"], label="val_loss")
plt.plot(np.arange(0, 100), H.history["accuracy"], label="train_acc")
plt.plot(np.arange(0, 100), H.history["val_accuracy"], label="val_acc")
plt.title("Training Loss and Accuracy")
plt.xlabel("Epoch #")
plt.ylabel("Loss/Accuracy")
plt.legend()
plt.savefig("plot.png")