# -*- coding: utf-8 -*-
"""cifar10_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VR03etA3fMLt2Mu4waN9VNiR-tqXqYFg

CIFAR10 데이터셋 로딩 및 추론을 할 때 필요한 파이썬 모듈을 임포팅하기
"""

from tensorflow.keras.models import load_model  # TensorFlow is required for Keras to work
import cv2  # Install opencv-python
import numpy as np

"""CIFAR10 추론 파일을 로드하기. 추론파일: 트레이닝을 통해 계수를 최적화한 인공신경망을 파일로 만들어 저장한 것. 이 추론파일을 사용해서 feedforward 측 추론/예측을 진행함.
코랩에서 추론파일을 사용할 때는 추론파일인 "cifar10.h5"을 코랩 디스크에 미리 업로드 해 놓아야 함

"""

# 추론 파일을 로드 함
model = load_model('./cifar10.h5')

labelNames = ["airplane", "automobile", "bird", "cat", "deer",
	"dog", "frog", "horse", "ship", "truck"]

"""내 이미지를 추론파일을 통해서 예측해 보기
이제 인터넷에서 CIFAR10 데이터 종류 중 하나를 선택해서 코랩으로 옮기기. OpenCV를 이용해서 인터넷에서 예를 들어'비행기'이미지를 코랩으로 업로드 함
"""

# 내가 판단할 이미지를 로드 OpenCV로 한다.
img = cv2.imread('plane.png')
cv2.imshow('win', img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

"""내 이미지 사이즈 조절하기.
CIFAR10 추론파일은 32x32x3인 이미지만 추론을 할 수 있음. 따라서 내 이미지의 사이즈를 32x32x3으로 축소해야 함. OpenCV 라이브러리를 이용해서 사이즈를 추론파일에 입력할 수 있도록 조정함
"""

img_resized = cv2.resize(img, (32,32))
cv2.imshow('win', img_resized)
cv2.waitKey(1000)
cv2.destroyAllWindows()

"""내 이미지 노말라이징
내가 업로드 한 이미지는 한 픽셀마다 3개의 0 ~ 255인 숫자로 구성되어 있음. 이 숫자의 범위를 0 ~ 1로 조정함. 이렇게 하면 feedforwarding 예측 성능이 향상됨
"""

# Normalizing
img_norm = img_resized.astype('float')/255.0
print(img_norm)

"""Flattening
내 이미지를 사이즈 조정 -> 노말라이징을 한 다음에는 이미지의 픽셀숫자 배열을 flattening을 함. 32x32x3인 이미지를 1x(32x32x3)으로 변경해야함 CIFAR10 신경망에 입력이 가능함   
"""

# flattening
img_flat = img_norm.reshape((3072,1))
#print(img_flat.shape)

"""추론하기
이제 내 이미지를 전처리해서 추론파일에 입력할 준비가 됨. 전처리된 내 이미지를 추론파일에 입력해서 예측을 실행
"""

# 추론하기, inference, feed-forward
## X -> img_flat에 []을 한번더 씌운 것
X = np.asarray([img_flat])
#print(X.shape)
# 여기서 입력이미지를 추론파일에 곱하는 것
## return 값은 softmax
predictions = model(X, training=False)
print(predictions)
print(np.argmax(predictions))