# -*- coding: utf-8 -*-
"""cifar10_cnn_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7zUnm6fMbPyxglKXlziYIq2-DSSFJnV

**구글 텐서플로 라이브러리 임포트** <br>
CIFAR10 데이터셋은 컬러 이미지셋이므로 기존 neural network로는 분류가 쉽지 않다. 따라서 이미지 분류 전용의 CNN을 사용하려 한다. CNN 역시 tensorflow계열의 딥러닝 라이브러리이므로 필요한 파이썬 라이브러리를 임포트한다.
"""

from tensorflow.keras.datasets import cifar10
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Activation
from sklearn.metrics import classification_report
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("✅ GPU 메모리 동적 할당 설정 완료")
    except RuntimeError as e:
        print(e)

"""**CIFAR10 데이터셋 다운로드** <br>|
CIFAR10 데이터셋은 이미지 딥러닝 교육에 많이 사용되는 데이터셋으로 구글의 파이썬 명령 하나로 서버에서 다운로드 받을 수 있다. trainX는 트레이닝용 입력 이미지 데이터(비행기 이미지), trainY는 입력 이미지의 결과값 (비행기) 이다. 이미지 사이즈는 32x32이다. trainX.shpae 명령으로 사이즈를 확인할 수 있다. testX, testY는 검증용 데이터셋 이다.
"""

((trainX, trainY), (testX, testY)) = cifar10.load_data()
# 입력 데이터인 trainX 사이즈를 확인하기
print(trainX.shape)
# 실제 입력데이터 60000개 중 첫번째것의 실제 이미지 데이터를 확인하기
print(trainX[0])
# 실제 출력데이터 60000개 중 첫번째것을 확인하기
print(trainY[0])

"""**입력 이미지 데이터 노말라이징** <br>
입력 이미지 데이터는 정수의 배열로 데이터가 구성되어 있다. 이 데이터는 0 ~ 255까지의 숫자이다. 이 숫자를 0 ~ 1사이의 값으로 변경하는 것이 텐서플로에서 처리하기 쉽다.노말라이징은 입력 이미지 데이터인 trainX, testX가 대상이다.
"""

trainX = trainX.astype("float")/255
testX = testX.astype("float")/255
# trainX[0]의 정수 데이터들이 노말라이징 된 것을 확인한다.
print(trainX[0])

"""**출력 데이터셋 라벨 바이나리징** <br>
CIFAR10 출력 데이터셋 즉 라벨값은 0 ~ 9사이의 정수이다. 이 정수를 바이너리 벡터화 하는 것이 라벨바이나리징인데 이것을 실행한다. <br>
2 -> [0 0 1 0 0 0 0 0 0 0 0]
"""

print(trainY[0])
lb = LabelBinarizer()
trainY = lb.fit_transform(trainY)
testY = lb.fit_transform(testY)
print(trainY[0]) # 라벨바이나리징 전후를 비교하기

"""**라벨 데이터의 숫자 맵핑** <br>
CIFAR10 10개의 데이터의 이름을 숫자와 맵핑한다. 여기서는 참고로만 사용한다. 실제 코드에는 사용하지 않는다.   
"""

labelNames = ["airplane", "automobile", "bird", "cat", "deer",
	"dog", "frog", "horse", "ship", "truck"]

"""**CNN 모델을 구성하기전 준비** <br>
CNN 모델을 구성하기 위해서 사전 준비를 한다. 먼저 경사하강법을 실행하는 옵티마이저는 SGD로 정한다. 러닝레이트는 0,01로 한다.입력 이미지는 32x32x3 이다.
"""

opt = SGD(learning_rate=0.01)

height = 32
width = 32
depth =3
model = Sequential()
inputShape = (height, width, depth)

"""모델의 구성 <br>
1개의 컨볼루션 레이어, 1개의 댄스레이어(기존 신경망 레이어)로 구성된 CNN 모델을 만든다. 컨볼루션 레이어의 액티베이션 함수는 relu, 댄스레이어의 액티베이션 함수는 softmax를 사용한다.
"""

model.add(Conv2D(32, (3, 3), padding="same", input_shape=inputShape))
model.add(Activation("relu"))
model.add(Flatten())
model.add(Dense(10))
model.add(Activation("softmax"))
model.summary()

"""**모델의 구성** <br>
옵티마이저, 손실함수, 메트릭을 정해주고 CNN 신경망을 구성한다.
"""

model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"] )

"""**모델 트레이닝** <br>
이제 CNN이 구성되었고, trainX, trainY 데이터셋을 이용해서 트레이닝 데이터를 진행한다. testX testY로 검증을 한다. 총 epochs는 40이다.
"""

H = model.fit(trainX, trainY, validation_data=(testX, testY), batch_size=32, epochs =40)

"""**트레이닝 결과 확인하기** <br>
트레이닝 한 결과를 확인한다. 실제로 CIFAR10 데이터셋은 CNN을 사용해도 예측률이 60$정도로 그리 좋지는 않다. 이것은 데이터셋의 해상도가 너무 낮고 데이터숫자가 많지 않아서 발생하는 현상이다.
"""

predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1),
	predictions.argmax(axis=1), target_names=labelNames))

"""**CNN 추론파일 저장하기** <br>
트레이닝된 추론파일을 다음에 사용하기 위해서 디스크에 저장한다.
"""

model.save('cifar10_cnn.h5')