# -*- coding: utf-8 -*-
"""mnist_tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqf0rWDHBsB7bg5orh6Bl2o1_CJDyeJz
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import classification_report
import cv2
import matplotlib.pyplot as plt
import numpy as np
import random

"""MNIST 데이터셋 딥러닝 트레이닝을 위한 필요한 파이썬 모듈 임포트"""

((trainX, trainY), (testX, testY)) = mnist.load_data()
print(trainX.shape)
print(trainY.shape)
((trainX10, trainY10), (testX10, testY10)) = cifar10.load_data()
print(trainX10.shape)
print(trainY10.shape)

"""MNIST 데이터셋을 다운로드하고 트레이닝용 데이터와 검증용 데이터로 나눈다."""

img = cv2.resize(trainX[0], (100, 100))
cv2.imshow('win', img)
cv2.waitKey(1)
cv2.destroyAllWindows()
print(trainY[0])
index = random.randint(0, 50000)
img = cv2.resize(trainX[index], (100, 100))
cv2.imshow('win2', img)
cv2.waitKey(1)
cv2.destroyAllWindows()
print(index)
print(trainY[index])

"""다운로드 된 MNIST 데이터 하나를 디스플레이 해서 보기"""

print('before flatenning', trainX.shape)
print('before flatenning',testX.shape)
trainX = trainX.reshape((trainX.shape[0], 28 * 28 * 1))
testX = testX.reshape((testX.shape[0], 28 * 28 * 1))
print(trainX.shape)
print(testX.shape)

"""50000 x 28 x 28 x 1 의 행렬 형태의 입력 데이터를 50000 x 784 x 1의 행렬로 만든다. Flattening.  """

print("Before normalizing: ", trainX[0])
trainX = trainX.astype("float32") / 255.0
testX = testX.astype("float32") / 255.0
print("After normalizing: ", trainX[0])

"""입력 데이터의 flattening 이후에는 입력 데이터를 normalizing한다. Normalizing이전에는 입력데이터 하나하나의 값이 0 ~ 255인데, normalizing이후에는 0~1로 변경된다."""

print("Before label binarizing (trainY[0]): ", trainY[0])
lb = LabelBinarizer()
trainY = lb.fit_transform(trainY)
testY = lb.transform(testY)
print("After label binarizing (trainY[0]): ", trainY[0])

sgd = SGD(0.01)
model = Sequential()
model.add(Dense(256, input_shape=(784,), activation="sigmoid"))
model.add(Dense(128, activation="sigmoid"))
model.add(Dense(10, activation="softmax"))

"""역전파를 수행하는 경사강하법을 효율적으로 하기 위해서 옵티마이저를 SGD를 사용한다.
텐서플로의 Sequencial 모듈을 사용해서 신경망을 구성한다.
신경망은 입력을 제외하고 2개의 레이어 (256, 128, 10) 3개의 레이어로 구성된다. 마지막 레이어는 출력 레이어로 출력은 10개이다.

"""

model.compile(loss="categorical_crossentropy", optimizer=sgd,
	metrics=["accuracy"])

"""Sequential로 구성한 신경망 모델은 compile 명령을 통해서 만들어진다. 이때 로스함수(에러함수), 경사강하법에 사용되는 옵티마이저, metrics를 입력한다."""

H = model.fit(trainX, trainY, validation_data=(testX, testY),
	epochs=100, batch_size=128)

"""fit 명령을 통해서 신경망 트레이닝을 진행한다. epochs에 지정된 회수만큼 트레이닝을 반복진행한다. batch_size는 한번에 신경망에 투입되는 입력값의 갯수이다."""

img = cv2.imread('2.png')
print(img.shape)
cv2.imshow('win', img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

"""신경망 트레이닝이 끝이나면 테스트를 위해서 숫자 이미지를 로드한다."""

img = cv2.resize(img, (28,28))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img.shape)
img = np.reshape(img, (784, ))

X = np.asarray([img])
predictions = model(X, training=False)
print(predictions)
print(np.argmax(predictions))

"""로드된 숫자 이미지를 신경망에 통과시켜서 숫자값을 예측해 본다. 트레이닝 데이터와 로드한 숫자 이미지 데이터를 비교해서 데이터가 제대로 학습이 되었는지 비교해볼 수 있다."""

print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=128)
print(classification_report(testY.argmax(axis=1),
	predictions.argmax(axis=1),
	target_names=[str(x) for x in lb.classes_]))

"""트레이닝된 신경망이 얼마나 정확한지 테스트 데이터셋으로 검증을 해본다."""

plt.style.use("ggplot")
plt.figure()
plt.plot(np.arange(0, 100), H.history["loss"], label="train_loss")
plt.plot(np.arange(0, 100), H.history["val_loss"], label="val_loss")
plt.plot(np.arange(0, 100), H.history["accuracy"], label="train_acc")
plt.plot(np.arange(0, 100), H.history["val_accuracy"], label="val_acc")
plt.title("Training Loss and Accuracy")
plt.xlabel("Epoch #")
plt.ylabel("Loss/Accuracy")
plt.legend()
plt.savefig('kera_mnist.png')
plt.show()

model.save("mnist.h5")

"""신경망의 학습 정확도를 그래픽으로 플로팅 해본다."""