# -*- coding: utf-8 -*-
"""mnist_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1msUfvWIydSuPrxS7oEfYKM8txW4n-B

추론 feed forward에 필요한 파이썬 모듈 로딩
"""

from tensorflow.keras.models import load_model  # TensorFlow is required for Keras to work
import cv2  # Install opencv-python
import numpy as np
from google.colab.patches import cv2_imshow

"""mnist 추론 파일을 로드하기. 추론파일은 트레이닝된 계수들의 배열임"""

# Load the model
model = load_model("mnist.h5", compile=False)

"""내가 만든 숫자 이미지를 로딩하기"""

image = cv2.imread('2.png')

"""로딩한 숫자를 확인하기"""

cv2_imshow(image)
cv2.waitKey(1000)
cv2.destroyAllWindows()

"""mnist 데이터에 맞게 리사이징 하기"""

image = cv2.resize(image, (28,28))
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(image.shape)

"""리사이즈한 이미지를 확인"""

cv2_imshow(image)
cv2.waitKey(1000)
cv2.destroyAllWindows()

"""이미지를 flattening 하기"""

print(image.shape)
image = np.reshape(image, (784, ))
#image = image.reshape((784, ))
print(image.shape)

"""노말라이징 하기"""

print(image)
image = image.astype('float')/255.0
print(image)

"""추론 파일에 입력해서 결과 얻기"""

X = np.asarray([image])
predictions = model(X, training=False)
print(predictions)
print(np.argmax(predictions))

"""추론한 결과 값에서 라벨값(숫자)를 얻기

"""

print(np.argmax(predictions))